<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net35</TargetFramework>
    <ApplicationIcon>../favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Binternal" PrivateAssets="all" />
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <PackageReference Include="PolyShim" PrivateAssets="all" />
    <PackageReference Include="PowerKit" Internalize="true" PrivateAssets="all" />
  </ItemGroup>
</Project>
